baseURL: "https://afonsoazaruja.github.io/"
languageCode: en-us
title: Afonso Azaruja
theme: ["PaperMod"]

params:
  profileMode:
    enabled: true
    title: "Under Construction" # optional default will be site title
    subtitle: ""
    imageUrl: "" # optional
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size

  socialIcons: # optional
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/afonsoazaruja/"
    - name: "GitHub"
      url: "https://github.com/afonsoazaruja/"