baseURL: "https://afonsoazaruja.github.io/"
languageCode: en-us
title: Afonso Azaruja
theme: ["PaperMod"]

params:
  profileMode:
    enabled: true
    title: "Afonso Azaruja"
    subtitle: "Student, Developer & Athlete"
    imageUrl: "/pic.jpg"
    imageTitle: "Picture"
    imageWidth: 120
    imageHeight: 120

  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/afonsoazaruja/"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/afonsoazaruja/"
    - name: "Email"
      url: "mailto:me@afonsoazaruja.pt"
 
  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: cv
      name: CV
      url: /cv/
      weight: 4
  
  
    